B.Tech in ECE

2.5+ years of exerience in OLE automation, Web Automation and Web Scraping using perl. 


Hi,

I have made scraper to scrape the provided information from sites. Please find attached sample xls file generated by script.

Please review the file and provide your comments if some data needs to be added.

Please get back to discuss further. Looking forward to hear back from you.

Thanks,
Kartik

Hi,

I have expertise in web scraping/web automation using perl. If possible could you please provide sample of url and output format.
I would like to provide you sample. If all is good, we could be able start the project based on mutual aggrement.


Thanks,
Kartik
